swagger: "2.0"
info:
  version: "0.49.2"
  title: Gramene API for release 49
# basePath prefixes all resource paths
basePath: /
# during dev, should point to your local machine
#host: localhost:10010/{basePath}
# 
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
  - application/xml
  - text/plain
paths:
  /docs:
    get:
      summary: "Web site describing this API"
      tags:
        - "API Documentation"
      responses:
        200:
          description: "HTML documentation for this web service, powered by swagger."
#  /ensembl:
#    get:
#      summary: "Proxy to Gramene's Ensembl REST installation"
#      description: "Please refer to rest.ensembl.org for documentation\n"
#      tags:
#        - "Ensembl REST"
#      responses:
#        200:
#          description: "Ensembl REST response"
#  /reactome:
#    get:
#      summary: "Proxy to Gramene's Plant Reactome REST API"
#      description: "Reactome RESTful API <a href='http://reactomews.oicr.on.ca:8080/ReactomeRESTfulAPI/ReactomeRESTFulAPI.html'>documentation</a>"
#      tags:
#        - "Plant Reactome REST"
#      responses:
#        200:
#          description: "plant reactome response"
#  /reactome/pathwayHierarchy/{species}:
#    get:
#      summary: "pathway hierarchy"
#      description: "Get the pathway hierarchy for a specified species as displayed in Reactome pathway browser."
#      tags:
#        - "Plant Reactome REST"
#      produces:
#        - "application/xml"
#      responses:
#        200:
#          description: "String - XML text containing pathways and reactions"
#      parameters:
#        -
#          name: "species"
#          in: "path"
#          description: "Full species name that should be encoded for URL (e.g. oryza+sativa, or zea+mays)"
#          type: "string"
#          required: true
  /search:
    x-swagger-router-controller: solr
    get:
      summary: "Gramene Data"
      operationId: genes
      description: "This is the entry point for searching our solr genes core.\n"
      parameters:
        -
          name: "q"
          in: "query"
          description: "query string."
          required: false
          type: "string"
        -
          name: "fl"
          in: "query"
          description: "List of fields to include in response (default all)."
          required: false
          type: "array"
          items:
            type: "string"
        -
          name: "wt"
          in: "query"
          description: "response format defaults to 'json'."
          enum:
            - "json"
            - "xml"
            - "csv"
            - "bed"
          type: "string"
          required: false
        - 
          name: "facet.field"
          in: "query"
          description: "Facet field parameters"
          required: false
          type: "array"
          items:
            type: "string"
        -
          name: "fq"
          in: "query"
          description: "Field query parameters"
          required: false
          type: "array"
          items:
            type: "string"
        -
          name: "json.facet"
          in: "query"
          description: "Supply all facets as a structured document."
          required: false
          type: "array"
          items:
            type: "string"
        -
          name: "rows"
          in: "query"
          description: "number of rows to return (default: 20)"
          required: false
          type: "integer"
        -
          name: "start"
          in: "query"
          description: "offset into results list"
          type: "integer"
          required: false
      tags:
        - "Search"
      responses:
        200:
          description: "Solr response object"
          schema:
            $ref: "#/definitions/SolrGeneResponse"
  /suggest:
    x-swagger-router-controller: solr
    get:
      summary: "Genes"
      operationId: suggestions
      description: "This is the entry point for searching our solr genes core.\n"
      parameters:
        -
          name: "q"
          in: "query"
          description: "query string."
          required: true
          type: "string"
        -
          name: "rows"
          in: "query"
          description: "number of rows to return (default: 20)"
          required: false
          type: "integer"
        -
          name: "start"
          in: "query"
          description: "offset into results list"
          type: "integer"
          required: false
      tags:
        - "Search"
      responses:
        200:
          description: "Solr response object"
  /{collection}:
    x-swagger-router-controller: mongo
    get: 
      summary: "MongoDB"
      operationId: get
      description: "Fetch documents from a collection"
      parameters: 
        - 
          name: "collection"
          in: "path"
          description: "name of collection"
          enum: 
            - "genes"
            - "genetrees"
            - "maps"
            - "domains"
            - "taxonomy"
            - "GO"
            - "PO"
          type: "string"
          required: true
        - 
          name: "q"
          in: "query"
          description: "string for free text search"
          type: "string"
          required: false
        - 
          name: "rows"
          in: "query"
          description: "number of rows to return (default: 20)"
          type: "integer"
          required: false
        - 
          name: "start"
          in: "query"
          description: "offset into results list"
          type: "integer"
          required: false
        - 
          name: "fl"
          in: "query"
          description: "list of fields to return"
          type: "array"
          items:
            type: "string"
          required: false
        - 
          name: "wt"
          in: "query"
          description: "response format, if `fl` is specified, this value may be either 'tab' or 'json'. If `fl` is not specified, this parameter is ignored and JSON documents are always returned."
          enum:
            - "json"
            - "tab"
            - ""
          type: "string"
          required: false
        - 
          name: "idList"
          in: "query"
          description: "a comma separated list of document ids"
          type: "array"
          items:
            type: "string"
          required: false
      tags: 
        - "Data access"
      responses: 
        200:
          description: "MongoDB response object"
  /swagger:
    x-swagger-pipe: swagger_raw
# complex objects have schema definitions
definitions:
  SolrGeneResponse:
    required:
     - responseHeader
     - response
    properties:
      responseHeader:
        type: object
        $ref: '#/definitions/SolrResponseHeader'
      response:
        type: object
        $ref: '#/definitions/SolrGeneResponseBody'
      facet_counts:
        type: object
        $ref: '#/definitions/SolrFacetDocument'
  SolrResponseHeader:
    required:
     - status
     - QTime
    properties:
      status:
        type: integer
      QTime:
        type: integer
  SolrGeneResponseBody:
    required:
      - start
      - maxScore
      - numFound
    properties:
      numFound:
        type: integer
      start:
        type: integer
      maxScore:
        type: integer
      docs:
        type: array
        items:
          type: object
          $ref: '#/definitions/SolrGeneDocument'
  SolrFacetDocument:
    required:
      - facet_queries
      - facet_fields
      - facet_dates
      - facet_ranges
      - facet_intervals
      - facet_heatmaps
    properties:
      facet_queries:
        type: object
      facet_fields:
        type: object
      facet_dates:
        type: object
      facet_ranges:
        type: object
      facet_intervals:
        type: object
      facet_heatmaps:
        type: object
  SolrGeneDocument:
    required:
      - id
      - name
      - description
      - taxon_id
      - biotype
      - score
    properties:
      id:
        type: string
      name:
        type: string
      description:
        type: string
      taxon_id:
        type: integer
        minimum: 0
      score:
        type: number
      biotype:
        type: string
        enum:
          - "protein_coding"
          - "miRNA"
          - "ncRNA"
          - "low_confidence"
          - "transposable_element"
          - "snoRNA"
          - "tRNA"
          - "misc_RNA"
          - "undefined"
          - "pseudogene"
          - "tRNA_pseudogene"
          - "nontranslating_CDS"
          - "snRNA"
          - "rRNA"
          - "antisense"
          - "SRP_RNA"
          - "tmRNA"
          - "ribozyme"
          - "RNase_MRP_RNA"
          - "telomerase_RNA"
          - "P_RNA"
          - "RNase_P_RNA"
          - "vault_RNA"
#  SolrSuggestionDocument:
